### ISSUE TITLE
Dont understand how to get the result from fft(int* x, double complex* X, uint16_t N) functions 

### ISSUE THREAD

**Issue by 123Dante123** [brendanashworth/fft-small#1]
Great work on this DFT and FFT implementation into a one piece of usable code for an embedded platform. Unfortunately, I don't understand how can I see the calculation result after putting my data into fft(int* x, double complex* X, uint16_t N) function?

**Comment by brendanashworth** [comment]
@123Dante123, it puts the frequency domain data into the second argument, [`double complex* X`](https://github.com/brendanashworth/fft-small/blob/8fa4634ff911f1b7f6624fc2ab7f408ada1ad958/fft.c#L36), which should be pre-allocated to have space for `N` complex numbers.
Let me know if you have any problems.
